import attr

@attr.s
class Submission(object):
    adsh = attr.ib(validator=[])
    cik = attr.ib(validator=[])
    name = attr.ib(validator=[])
    sic = attr.ib(validator=[])
    countryba = attr.ib(validator=[])
    stprba = attr.ib(validator=[])
    cityba = attr.ib(validator=[])
    zipba = attr.ib(validator=[])
    bas1 = attr.ib(validator=[])
    bas2 = attr.ib(validator=[])
    baph = attr.ib(validator=[])
    countryma = attr.ib(validator=[])
    stprma = attr.ib(validator=[])
    cityma = attr.ib(validator=[])
    zipma = attr.ib(validator=[])
    mas1 = attr.ib(validator=[])
    mas2 = attr.ib(validator=[])
    countryinc = attr.ib(validator=[])
    stprinc = attr.ib(validator=[])
    ein = attr.ib(validator=[])
    former = attr.ib(validator=[])
    changed = attr.ib(validator=[])
    afs = attr.ib(validator=[])
    wksi = attr.ib(validator=[])
    fye = attr.ib(validator=[])
    form = attr.ib(validator=[])
    period = attr.ib(validator=[])
    fy = attr.ib(validator=[])
    fp = attr.ib(validator=[])
    filed = attr.ib(validator=[])
    accepted = attr.ib(validator=[])
    prevrpt = attr.ib(validator=[])
    detail = attr.ib(validator=[])
    instance = attr.ib(validator=[])
    nciks = attr.ib(validator=[])
    aciks = attr.ib(validator=[])

